org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5

# Mod Properties
mod_version=1.0.1
maven_group=com.redtracx
archives_base_name=skyblock-chat-filter

# Dependencies
fabric_version=0.104.0+1.21.1

org.gradle.java.home=C:/Users/mahrn/Downloads/java-21-openjdk-21.0.4.0.7-1.win.jdk.x86_64/java-21-openjdk-21.0.4.0.7-1.win.jdk.x86_64